### PR TITLE
Support linking against system liblzma

### PR DESCRIPTION
**Pull request by cssivision**
fix https://github.com/alexcrichton/xz2-rs/issues/16

### CODE REVIEW

**Comment by cssivision** [comment]
vcpkg tree with liblzma installed for target `msvc`?

**Comment by alexcrichton** [comment]
Thanks! I think it's ok to not add vcpkg just yet. Could you add a test on CI which exercises this though?

**Comment by cssivision** [comment]
fixed ci.

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
